rcmysql status
rcapache2 status
rcobsrepserver status
#rcobsworker status
rcobsscheduler status
rcobsservice status
#rcobssignd status
#rcobsapidelayed status
#rcobssigner status
rcobsapisetup status
rcobssrcserver status
rcobsdispatcher status
rcobsstoragesetup status
rcobspublisher status
rcobswarden status
rcobssrcserver status
rcobsrepserver status
rcobspublisher status
