rcmysql start
rcapache2 start
rcobsrepserver start
#rcobsworker start
rcobsscheduler start
rcobsservice start
#rcobssignd start
#rcobsapidelayed start
#rcobssigner start
rcobsapisetup start
rcobssrcserver start
rcobsdispatcher start
rcobsstoragesetup start
rcobspublisher start
rcobswarden start
rcobssrcserver start
rcobsrepserver start
rcobspublisher start
