FROM opensuse/leap:15.1
MAINTAINER tommylike <tommylikehu@gmail.com>
RUN zypper ar -f https://download.opensuse.org/repositories/OBS:/Server:/2.10/openSUSE_15.1/OBS:Server:2.10.repo \
    && zypper in -y -t pattern OBS_Server
